(DEFPACKAGE :ZXDG-SHELL-V6-SERVER-PROTOCOL
  (:USE :COMMON-LISP
        :CFFI
        :WAYLAND-UTIL
        :WAYLAND-SERVER-CORE
        :WAYLAND-SERVER-PROTOCOL)
  (:EXPORT ZXDG-SHELL-V6-INTERFACE
           ZXDG-SHELL-V6-IMPLEMENTATION
           EMPTY-ZXDG-SHELL-V6-DESTROY
           EMPTY-ZXDG-SHELL-V6-CREATE-POSITIONER
           EMPTY-ZXDG-SHELL-V6-GET-XDG-SURFACE
           EMPTY-ZXDG-SHELL-V6-PONG
           IMPLEMENT-ZXDG-SHELL-V6
           ZXDG-SHELL-V6-SEND-PING
           ZXDG-POSITIONER-V6-INTERFACE
           ZXDG-POSITIONER-V6-IMPLEMENTATION
           EMPTY-ZXDG-POSITIONER-V6-DESTROY
           EMPTY-ZXDG-POSITIONER-V6-SET-SIZE
           EMPTY-ZXDG-POSITIONER-V6-SET-ANCHOR-RECT
           EMPTY-ZXDG-POSITIONER-V6-SET-ANCHOR
           EMPTY-ZXDG-POSITIONER-V6-SET-GRAVITY
           EMPTY-ZXDG-POSITIONER-V6-SET-CONSTRAINT-ADJUSTMENT
           EMPTY-ZXDG-POSITIONER-V6-SET-OFFSET
           IMPLEMENT-ZXDG-POSITIONER-V6
           ZXDG-SURFACE-V6-INTERFACE
           ZXDG-SURFACE-V6-IMPLEMENTATION
           EMPTY-ZXDG-SURFACE-V6-DESTROY
           EMPTY-ZXDG-SURFACE-V6-GET-TOPLEVEL
           EMPTY-ZXDG-SURFACE-V6-GET-POPUP
           EMPTY-ZXDG-SURFACE-V6-SET-WINDOW-GEOMETRY
           EMPTY-ZXDG-SURFACE-V6-ACK-CONFIGURE
           IMPLEMENT-ZXDG-SURFACE-V6
           ZXDG-SURFACE-V6-SEND-CONFIGURE
           ZXDG-TOPLEVEL-V6-INTERFACE
           ZXDG-TOPLEVEL-V6-IMPLEMENTATION
           EMPTY-ZXDG-TOPLEVEL-V6-DESTROY
           EMPTY-ZXDG-TOPLEVEL-V6-SET-PARENT
           EMPTY-ZXDG-TOPLEVEL-V6-SET-TITLE
           EMPTY-ZXDG-TOPLEVEL-V6-SET-APP-ID
           EMPTY-ZXDG-TOPLEVEL-V6-SHOW-WINDOW-MENU
           EMPTY-ZXDG-TOPLEVEL-V6-MOVE
           EMPTY-ZXDG-TOPLEVEL-V6-RESIZE
           EMPTY-ZXDG-TOPLEVEL-V6-SET-MAX-SIZE
           EMPTY-ZXDG-TOPLEVEL-V6-SET-MIN-SIZE
           EMPTY-ZXDG-TOPLEVEL-V6-SET-MAXIMIZED
           EMPTY-ZXDG-TOPLEVEL-V6-UNSET-MAXIMIZED
           EMPTY-ZXDG-TOPLEVEL-V6-SET-FULLSCREEN
           EMPTY-ZXDG-TOPLEVEL-V6-UNSET-FULLSCREEN
           EMPTY-ZXDG-TOPLEVEL-V6-SET-MINIMIZED
           IMPLEMENT-ZXDG-TOPLEVEL-V6
           ZXDG-TOPLEVEL-V6-SEND-CONFIGURE
           ZXDG-TOPLEVEL-V6-SEND-CLOSE
           ZXDG-POPUP-V6-INTERFACE
           ZXDG-POPUP-V6-IMPLEMENTATION
           EMPTY-ZXDG-POPUP-V6-DESTROY
           EMPTY-ZXDG-POPUP-V6-GRAB
           IMPLEMENT-ZXDG-POPUP-V6
           ZXDG-POPUP-V6-SEND-CONFIGURE
           ZXDG-POPUP-V6-SEND-POPUP-DONE
           ZXDG-SHELL-V6-SERVER-TYPES
           INITIALIZE-ZXDG-SHELL-V6-SERVER-INTERFACES))

(IN-PACKAGE :ZXDG-SHELL-V6-SERVER-PROTOCOL)

(DEFPARAMETER ZXDG-SHELL-V6-INTERFACE NIL)

(DEFCSTRUCT ZXDG-SHELL-V6-IMPLEMENTATION (DESTROY :POINTER)
 (CREATE-POSITIONER :POINTER) (GET-XDG-SURFACE :POINTER) (PONG :POINTER))

(DEFCALLBACK EMPTY-ZXDG-SHELL-V6-DESTROY :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-SHELL-V6-CREATE-POSITIONER :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (ID :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-SHELL-V6-GET-XDG-SURFACE :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (ID :POINTER) (SURFACE :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-SHELL-V6-PONG :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (SERIAL :UINT32)))

(DEFUN IMPLEMENT-ZXDG-SHELL-V6
       (
        &KEY (DESTROY NIL) (CREATE-POSITIONER NIL) (GET-XDG-SURFACE NIL)
        (PONG NIL))
  (LET ((IMPLEMENTATION
         (FOREIGN-ALLOC '(:STRUCT ZXDG-SHELL-V6-IMPLEMENTATION))))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-SHELL-V6-IMPLEMENTATION) 'DESTROY)
            (IF DESTROY
                DESTROY
                (GET-CALLBACK 'EMPTY-ZXDG-SHELL-V6-DESTROY)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-SHELL-V6-IMPLEMENTATION) 'CREATE-POSITIONER)
            (IF CREATE-POSITIONER
                CREATE-POSITIONER
                (GET-CALLBACK 'EMPTY-ZXDG-SHELL-V6-CREATE-POSITIONER)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-SHELL-V6-IMPLEMENTATION) 'GET-XDG-SURFACE)
            (IF GET-XDG-SURFACE
                GET-XDG-SURFACE
                (GET-CALLBACK 'EMPTY-ZXDG-SHELL-V6-GET-XDG-SURFACE)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-SHELL-V6-IMPLEMENTATION) 'PONG)
            (IF PONG
                PONG
                (GET-CALLBACK 'EMPTY-ZXDG-SHELL-V6-PONG)))
    IMPLEMENTATION))

(DEFUN ZXDG-SHELL-V6-SEND-PING (RESOURCE SERIAL)
  (WL-RESOURCE-POST-EVENT RESOURCE 0 :UINT32 SERIAL))

(DEFPARAMETER ZXDG-POSITIONER-V6-INTERFACE NIL)

(DEFCSTRUCT ZXDG-POSITIONER-V6-IMPLEMENTATION (DESTROY :POINTER)
 (SET-SIZE :POINTER) (SET-ANCHOR-RECT :POINTER) (SET-ANCHOR :POINTER)
 (SET-GRAVITY :POINTER) (SET-CONSTRAINT-ADJUSTMENT :POINTER)
 (SET-OFFSET :POINTER))

(DEFCALLBACK EMPTY-ZXDG-POSITIONER-V6-DESTROY :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-POSITIONER-V6-SET-SIZE :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (WIDTH :INT32) (HEIGHT :INT32)))

(DEFCALLBACK EMPTY-ZXDG-POSITIONER-V6-SET-ANCHOR-RECT :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (X :INT32) (Y :INT32) (WIDTH :INT32)
  (HEIGHT :INT32)))

(DEFCALLBACK EMPTY-ZXDG-POSITIONER-V6-SET-ANCHOR :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (ANCHOR :UINT32)))

(DEFCALLBACK EMPTY-ZXDG-POSITIONER-V6-SET-GRAVITY :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (GRAVITY :UINT32)))

(DEFCALLBACK EMPTY-ZXDG-POSITIONER-V6-SET-CONSTRAINT-ADJUSTMENT :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (CONSTRAINT-ADJUSTMENT :UINT32)))

(DEFCALLBACK EMPTY-ZXDG-POSITIONER-V6-SET-OFFSET :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (X :INT32) (Y :INT32)))

(DEFUN IMPLEMENT-ZXDG-POSITIONER-V6
       (
        &KEY (DESTROY NIL) (SET-SIZE NIL) (SET-ANCHOR-RECT NIL)
        (SET-ANCHOR NIL) (SET-GRAVITY NIL) (SET-CONSTRAINT-ADJUSTMENT NIL)
        (SET-OFFSET NIL))
  (LET ((IMPLEMENTATION
         (FOREIGN-ALLOC '(:STRUCT ZXDG-POSITIONER-V6-IMPLEMENTATION))))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-POSITIONER-V6-IMPLEMENTATION) 'DESTROY)
            (IF DESTROY
                DESTROY
                (GET-CALLBACK 'EMPTY-ZXDG-POSITIONER-V6-DESTROY)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-POSITIONER-V6-IMPLEMENTATION) 'SET-SIZE)
            (IF SET-SIZE
                SET-SIZE
                (GET-CALLBACK 'EMPTY-ZXDG-POSITIONER-V6-SET-SIZE)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-POSITIONER-V6-IMPLEMENTATION) 'SET-ANCHOR-RECT)
            (IF SET-ANCHOR-RECT
                SET-ANCHOR-RECT
                (GET-CALLBACK 'EMPTY-ZXDG-POSITIONER-V6-SET-ANCHOR-RECT)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-POSITIONER-V6-IMPLEMENTATION) 'SET-ANCHOR)
            (IF SET-ANCHOR
                SET-ANCHOR
                (GET-CALLBACK 'EMPTY-ZXDG-POSITIONER-V6-SET-ANCHOR)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-POSITIONER-V6-IMPLEMENTATION) 'SET-GRAVITY)
            (IF SET-GRAVITY
                SET-GRAVITY
                (GET-CALLBACK 'EMPTY-ZXDG-POSITIONER-V6-SET-GRAVITY)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-POSITIONER-V6-IMPLEMENTATION)
           'SET-CONSTRAINT-ADJUSTMENT)
            (IF SET-CONSTRAINT-ADJUSTMENT
                SET-CONSTRAINT-ADJUSTMENT
                (GET-CALLBACK
                 'EMPTY-ZXDG-POSITIONER-V6-SET-CONSTRAINT-ADJUSTMENT)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-POSITIONER-V6-IMPLEMENTATION) 'SET-OFFSET)
            (IF SET-OFFSET
                SET-OFFSET
                (GET-CALLBACK 'EMPTY-ZXDG-POSITIONER-V6-SET-OFFSET)))
    IMPLEMENTATION))

(DEFPARAMETER ZXDG-SURFACE-V6-INTERFACE NIL)

(DEFCSTRUCT ZXDG-SURFACE-V6-IMPLEMENTATION (DESTROY :POINTER)
 (GET-TOPLEVEL :POINTER) (GET-POPUP :POINTER) (SET-WINDOW-GEOMETRY :POINTER)
 (ACK-CONFIGURE :POINTER))

(DEFCALLBACK EMPTY-ZXDG-SURFACE-V6-DESTROY :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-SURFACE-V6-GET-TOPLEVEL :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (ID :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-SURFACE-V6-GET-POPUP :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (ID :POINTER) (PARENT :POINTER)
  (POSITIONER :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-SURFACE-V6-SET-WINDOW-GEOMETRY :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (X :INT32) (Y :INT32) (WIDTH :INT32)
  (HEIGHT :INT32)))

(DEFCALLBACK EMPTY-ZXDG-SURFACE-V6-ACK-CONFIGURE :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (SERIAL :UINT32)))

(DEFUN IMPLEMENT-ZXDG-SURFACE-V6
       (
        &KEY (DESTROY NIL) (GET-TOPLEVEL NIL) (GET-POPUP NIL)
        (SET-WINDOW-GEOMETRY NIL) (ACK-CONFIGURE NIL))
  (LET ((IMPLEMENTATION
         (FOREIGN-ALLOC '(:STRUCT ZXDG-SURFACE-V6-IMPLEMENTATION))))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-SURFACE-V6-IMPLEMENTATION) 'DESTROY)
            (IF DESTROY
                DESTROY
                (GET-CALLBACK 'EMPTY-ZXDG-SURFACE-V6-DESTROY)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-SURFACE-V6-IMPLEMENTATION) 'GET-TOPLEVEL)
            (IF GET-TOPLEVEL
                GET-TOPLEVEL
                (GET-CALLBACK 'EMPTY-ZXDG-SURFACE-V6-GET-TOPLEVEL)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-SURFACE-V6-IMPLEMENTATION) 'GET-POPUP)
            (IF GET-POPUP
                GET-POPUP
                (GET-CALLBACK 'EMPTY-ZXDG-SURFACE-V6-GET-POPUP)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-SURFACE-V6-IMPLEMENTATION) 'SET-WINDOW-GEOMETRY)
            (IF SET-WINDOW-GEOMETRY
                SET-WINDOW-GEOMETRY
                (GET-CALLBACK 'EMPTY-ZXDG-SURFACE-V6-SET-WINDOW-GEOMETRY)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-SURFACE-V6-IMPLEMENTATION) 'ACK-CONFIGURE)
            (IF ACK-CONFIGURE
                ACK-CONFIGURE
                (GET-CALLBACK 'EMPTY-ZXDG-SURFACE-V6-ACK-CONFIGURE)))
    IMPLEMENTATION))

(DEFUN ZXDG-SURFACE-V6-SEND-CONFIGURE (RESOURCE SERIAL)
  (WL-RESOURCE-POST-EVENT RESOURCE 0 :UINT32 SERIAL))

(DEFPARAMETER ZXDG-TOPLEVEL-V6-INTERFACE NIL)

(DEFCSTRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION (DESTROY :POINTER)
 (SET-PARENT :POINTER) (SET-TITLE :POINTER) (SET-APP-ID :POINTER)
 (SHOW-WINDOW-MENU :POINTER) (MOVE :POINTER) (RESIZE :POINTER)
 (SET-MAX-SIZE :POINTER) (SET-MIN-SIZE :POINTER) (SET-MAXIMIZED :POINTER)
 (UNSET-MAXIMIZED :POINTER) (SET-FULLSCREEN :POINTER)
 (UNSET-FULLSCREEN :POINTER) (SET-MINIMIZED :POINTER))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-DESTROY :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-SET-PARENT :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (PARENT :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-SET-TITLE :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (TITLE :STRING)))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-SET-APP-ID :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (APP-ID :STRING)))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-SHOW-WINDOW-MENU :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (SEAT :POINTER) (SERIAL :UINT32)
  (X :INT32) (Y :INT32)))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-MOVE :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (SEAT :POINTER) (SERIAL :UINT32)))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-RESIZE :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (SEAT :POINTER) (SERIAL :UINT32)
  (EDGES :UINT32)))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-SET-MAX-SIZE :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (WIDTH :INT32) (HEIGHT :INT32)))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-SET-MIN-SIZE :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (WIDTH :INT32) (HEIGHT :INT32)))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-SET-MAXIMIZED :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-UNSET-MAXIMIZED :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-SET-FULLSCREEN :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (OUTPUT :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-UNSET-FULLSCREEN :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-TOPLEVEL-V6-SET-MINIMIZED :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER)))

(DEFUN IMPLEMENT-ZXDG-TOPLEVEL-V6
       (
        &KEY (DESTROY NIL) (SET-PARENT NIL) (SET-TITLE NIL) (SET-APP-ID NIL)
        (SHOW-WINDOW-MENU NIL) (MOVE NIL) (RESIZE NIL) (SET-MAX-SIZE NIL)
        (SET-MIN-SIZE NIL) (SET-MAXIMIZED NIL) (UNSET-MAXIMIZED NIL)
        (SET-FULLSCREEN NIL) (UNSET-FULLSCREEN NIL) (SET-MINIMIZED NIL))
  (LET ((IMPLEMENTATION
         (FOREIGN-ALLOC '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION))))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'DESTROY)
            (IF DESTROY
                DESTROY
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-DESTROY)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'SET-PARENT)
            (IF SET-PARENT
                SET-PARENT
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-SET-PARENT)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'SET-TITLE)
            (IF SET-TITLE
                SET-TITLE
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-SET-TITLE)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'SET-APP-ID)
            (IF SET-APP-ID
                SET-APP-ID
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-SET-APP-ID)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'SHOW-WINDOW-MENU)
            (IF SHOW-WINDOW-MENU
                SHOW-WINDOW-MENU
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-SHOW-WINDOW-MENU)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'MOVE)
            (IF MOVE
                MOVE
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-MOVE)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'RESIZE)
            (IF RESIZE
                RESIZE
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-RESIZE)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'SET-MAX-SIZE)
            (IF SET-MAX-SIZE
                SET-MAX-SIZE
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-SET-MAX-SIZE)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'SET-MIN-SIZE)
            (IF SET-MIN-SIZE
                SET-MIN-SIZE
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-SET-MIN-SIZE)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'SET-MAXIMIZED)
            (IF SET-MAXIMIZED
                SET-MAXIMIZED
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-SET-MAXIMIZED)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'UNSET-MAXIMIZED)
            (IF UNSET-MAXIMIZED
                UNSET-MAXIMIZED
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-UNSET-MAXIMIZED)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'SET-FULLSCREEN)
            (IF SET-FULLSCREEN
                SET-FULLSCREEN
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-SET-FULLSCREEN)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'UNSET-FULLSCREEN)
            (IF UNSET-FULLSCREEN
                UNSET-FULLSCREEN
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-UNSET-FULLSCREEN)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-TOPLEVEL-V6-IMPLEMENTATION) 'SET-MINIMIZED)
            (IF SET-MINIMIZED
                SET-MINIMIZED
                (GET-CALLBACK 'EMPTY-ZXDG-TOPLEVEL-V6-SET-MINIMIZED)))
    IMPLEMENTATION))

(DEFUN ZXDG-TOPLEVEL-V6-SEND-CONFIGURE (RESOURCE WIDTH HEIGHT STATES)
  (WL-RESOURCE-POST-EVENT RESOURCE 0 :INT32 WIDTH :INT32 HEIGHT :POINTER
   STATES))

(DEFUN ZXDG-TOPLEVEL-V6-SEND-CLOSE (RESOURCE)
  (WL-RESOURCE-POST-EVENT RESOURCE 1))

(DEFPARAMETER ZXDG-POPUP-V6-INTERFACE NIL)

(DEFCSTRUCT ZXDG-POPUP-V6-IMPLEMENTATION (DESTROY :POINTER) (GRAB :POINTER))

(DEFCALLBACK EMPTY-ZXDG-POPUP-V6-DESTROY :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER)))

(DEFCALLBACK EMPTY-ZXDG-POPUP-V6-GRAB :VOID
 ((CLIENT :POINTER) (RESOURCE :POINTER) (SEAT :POINTER) (SERIAL :UINT32)))

(DEFUN IMPLEMENT-ZXDG-POPUP-V6 (&KEY (DESTROY NIL) (GRAB NIL))
  (LET ((IMPLEMENTATION
         (FOREIGN-ALLOC '(:STRUCT ZXDG-POPUP-V6-IMPLEMENTATION))))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-POPUP-V6-IMPLEMENTATION) 'DESTROY)
            (IF DESTROY
                DESTROY
                (GET-CALLBACK 'EMPTY-ZXDG-POPUP-V6-DESTROY)))
    (SETF (FOREIGN-SLOT-VALUE IMPLEMENTATION
           '(:STRUCT ZXDG-POPUP-V6-IMPLEMENTATION) 'GRAB)
            (IF GRAB
                GRAB
                (GET-CALLBACK 'EMPTY-ZXDG-POPUP-V6-GRAB)))
    IMPLEMENTATION))

(DEFUN ZXDG-POPUP-V6-SEND-CONFIGURE (RESOURCE X Y WIDTH HEIGHT)
  (WL-RESOURCE-POST-EVENT RESOURCE 0 :INT32 X :INT32 Y :INT32 WIDTH :INT32
   HEIGHT))

(DEFUN ZXDG-POPUP-V6-SEND-POPUP-DONE (RESOURCE)
  (WL-RESOURCE-POST-EVENT RESOURCE 1))

(DEFPARAMETER ZXDG-SHELL-V6-SERVER-TYPES NIL)

(DEFUN INITIALIZE-ZXDG-SHELL-V6-SERVER-INTERFACES ()
  (SETF ZXDG-SHELL-V6-INTERFACE
          (MAKE-WL-INTERFACE "zxdg_shell_v6" 1 4 (NULL-POINTER) 1
           (NULL-POINTER)))
  (SETF ZXDG-POSITIONER-V6-INTERFACE
          (MAKE-WL-INTERFACE "zxdg_positioner_v6" 1 7 (NULL-POINTER) 0
           (NULL-POINTER)))
  (SETF ZXDG-SURFACE-V6-INTERFACE
          (MAKE-WL-INTERFACE "zxdg_surface_v6" 1 5 (NULL-POINTER) 1
           (NULL-POINTER)))
  (SETF ZXDG-TOPLEVEL-V6-INTERFACE
          (MAKE-WL-INTERFACE "zxdg_toplevel_v6" 1 14 (NULL-POINTER) 2
           (NULL-POINTER)))
  (SETF ZXDG-POPUP-V6-INTERFACE
          (MAKE-WL-INTERFACE "zxdg_popup_v6" 1 2 (NULL-POINTER) 2
           (NULL-POINTER)))
  (SETF ZXDG-SHELL-V6-SERVER-TYPES
          (MAKE-WL-TYPES (NULL-POINTER) ZXDG-POSITIONER-V6-INTERFACE
           ZXDG-SURFACE-V6-INTERFACE WL-SURFACE-INTERFACE (NULL-POINTER)
           (NULL-POINTER) (NULL-POINTER) (NULL-POINTER) (NULL-POINTER)
           (NULL-POINTER) (NULL-POINTER) (NULL-POINTER) (NULL-POINTER)
           (NULL-POINTER) (NULL-POINTER) (NULL-POINTER) (NULL-POINTER)
           ZXDG-TOPLEVEL-V6-INTERFACE ZXDG-POPUP-V6-INTERFACE
           ZXDG-SURFACE-V6-INTERFACE ZXDG-POSITIONER-V6-INTERFACE
           (NULL-POINTER) (NULL-POINTER) (NULL-POINTER) (NULL-POINTER)
           (NULL-POINTER) (NULL-POINTER) ZXDG-TOPLEVEL-V6-INTERFACE
           (NULL-POINTER) (NULL-POINTER) WL-SEAT-INTERFACE (NULL-POINTER)
           (NULL-POINTER) (NULL-POINTER) WL-SEAT-INTERFACE (NULL-POINTER)
           WL-SEAT-INTERFACE (NULL-POINTER) (NULL-POINTER) (NULL-POINTER)
           (NULL-POINTER) (NULL-POINTER) (NULL-POINTER) WL-OUTPUT-INTERFACE
           (NULL-POINTER) (NULL-POINTER) (NULL-POINTER) WL-SEAT-INTERFACE
           (NULL-POINTER) (NULL-POINTER) (NULL-POINTER) (NULL-POINTER)
           (NULL-POINTER)))
  (SET-REQUESTS ZXDG-SHELL-V6-INTERFACE
   (MAKE-WL-MESSAGE (LIST "destroy" "" ZXDG-SHELL-V6-SERVER-TYPES)
    (LIST "create_positioner" "n" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 1))
    (LIST "get_xdg_surface" "no" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 2))
    (LIST "pong" "u" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 4))))
  (SET-EVENTS ZXDG-SHELL-V6-INTERFACE
   (MAKE-WL-MESSAGE
    (LIST "ping" "u" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 5))))
  (SET-REQUESTS ZXDG-POSITIONER-V6-INTERFACE
   (MAKE-WL-MESSAGE (LIST "destroy" "" ZXDG-SHELL-V6-SERVER-TYPES)
    (LIST "set_size" "ii" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 6))
    (LIST "set_anchor_rect" "iiii" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 8))
    (LIST "set_anchor" "u" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 12))
    (LIST "set_gravity" "u" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 13))
    (LIST "set_constraint_adjustment" "u"
          (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 14))
    (LIST "set_offset" "ii" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 15))))
  (SET-EVENTS ZXDG-POSITIONER-V6-INTERFACE (MAKE-WL-MESSAGE))
  (SET-REQUESTS ZXDG-SURFACE-V6-INTERFACE
   (MAKE-WL-MESSAGE (LIST "destroy" "" ZXDG-SHELL-V6-SERVER-TYPES)
    (LIST "get_toplevel" "n" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 17))
    (LIST "get_popup" "noo" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 18))
    (LIST "set_window_geometry" "iiii"
          (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 21))
    (LIST "ack_configure" "u" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 25))))
  (SET-EVENTS ZXDG-SURFACE-V6-INTERFACE
   (MAKE-WL-MESSAGE
    (LIST "configure" "u" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 26))))
  (SET-REQUESTS ZXDG-TOPLEVEL-V6-INTERFACE
   (MAKE-WL-MESSAGE (LIST "destroy" "" ZXDG-SHELL-V6-SERVER-TYPES)
    (LIST "set_parent" "?o" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 27))
    (LIST "set_title" "s" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 28))
    (LIST "set_app_id" "s" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 29))
    (LIST "show_window_menu" "ouii" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 30))
    (LIST "move" "ou" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 34))
    (LIST "resize" "ouu" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 36))
    (LIST "set_max_size" "ii" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 39))
    (LIST "set_min_size" "ii" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 41))
    (LIST "set_maximized" "" ZXDG-SHELL-V6-SERVER-TYPES)
    (LIST "unset_maximized" "" ZXDG-SHELL-V6-SERVER-TYPES)
    (LIST "set_fullscreen" "?o" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 43))
    (LIST "unset_fullscreen" "" ZXDG-SHELL-V6-SERVER-TYPES)
    (LIST "set_minimized" "" ZXDG-SHELL-V6-SERVER-TYPES)))
  (SET-EVENTS ZXDG-TOPLEVEL-V6-INTERFACE
   (MAKE-WL-MESSAGE
    (LIST "configure" "iia" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 44))
    (LIST "close" "" ZXDG-SHELL-V6-SERVER-TYPES)))
  (SET-REQUESTS ZXDG-POPUP-V6-INTERFACE
   (MAKE-WL-MESSAGE (LIST "destroy" "" ZXDG-SHELL-V6-SERVER-TYPES)
    (LIST "grab" "ou" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 47))))
  (SET-EVENTS ZXDG-POPUP-V6-INTERFACE
   (MAKE-WL-MESSAGE
    (LIST "configure" "iiii" (OFFSET-TYPES ZXDG-SHELL-V6-SERVER-TYPES 49))
    (LIST "popup_done" "" ZXDG-SHELL-V6-SERVER-TYPES))))

